version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - gosec         # Security-focused linter
    - revive        # Fast and drop-in replacement for golint
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.ReadCloser).Close
        - (io.Closer).Close
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    govet:
      enable:
        - assign
        - atomic
        - bools
        - buildtag
        - nilfunc
        - printf
    gosec:
      # G104 is often too noisy as it flags every unchecked error which errcheck already handles
      excludes:
        - G104
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - linters:
          - staticcheck
        text: "SA9003:"
      - linters:
          - revive
        text: "unused-parameter"

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
